<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
		 <DefineConstants>NET48</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		 <DefineConstants>NET9_0</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">	
		<PackageReference Include="Syncfusion.PresentationRenderer.NET" Version="30.1.37" />
		<PackageReference Include="Syncfusion.Pdf.NET" Version="30.1.37" />
		<PackageReference Include="Syncfusion.Presentation.NET" Version="30.1.37" />
		<PackageReference Include="Syncfusion.XlsIO.NET" Version="30.1.37" />
		<PackageReference Include="Syncfusion.XlsIORenderer.NET" Version="30.1.37" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="Syncfusion.ExcelChartToImageConverter.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.ExcelToPdfConverter.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.OfficeChartToImageConverter.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.Pdf.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.PdfToImageConverter.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.Presentation.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.PresentationToPdfConverter.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.XlsIO.AspNet.Mvc5" Version="30.1.37" />
		<PackageReference Include="Syncfusion.ExcelChartToImageConverter.WinForms" Version="30.1.37" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Syncfusion.Licensing" Version="30.1.37" />
	</ItemGroup>

</Project>
